CREATE TABLE [dbo].[gold_outlier_training_data] (

	[ProductID] int NULL, 
	[ProductName] varchar(8000) NULL, 
	[CategoryID] int NULL, 
	[CategoryName] varchar(8000) NULL, 
	[AccountTypeID] int NULL, 
	[PricePerUnit] decimal(10,2) NULL, 
	[EffectivePricePerUnit] decimal(21,8) NULL, 
	[Quantity] int NULL, 
	[Discount] decimal(5,2) NULL, 
	[avg_price_per_unit] decimal(25,12) NULL, 
	[stddev_price_per_unit] float NULL, 
	[price_z_score] float NULL, 
	[price_percentile] float NULL, 
	[price_deviation_pct] decimal(38,8) NULL, 
	[day_of_week] varchar(8000) NULL, 
	[month] int NULL, 
	[State] varchar(8000) NULL, 
	[is_outlier] bit NULL, 
	[outlier_type] varchar(8000) NULL, 
	[outlier_severity] varchar(8000) NULL, 
	[outlier_score] int NULL, 
	[OrderID] int NULL, 
	[OrderItemID] int NULL, 
	[CustomerID] int NULL, 
	[OrderDate] datetime2(6) NULL
);